#!/usr/bin/env bash
#!/usr/bin/env bash
# - Install nginx on your web-01 server
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page) using curl,
#   it must return a page that contains the string Hello World
# - As an answer file, write a Bash script that configures a new Ubuntu machine to respect
#   above requirements (this script will be run on the server itself)
# - You can’t use systemctl for restarting nginx

if [ ! -x /usr/sbin/nginx ]; then
    sudo apt -y update
    sudo apt install -y --allow-downgrades nginx
    sudo ufw allow 'Nginx HTTP'
fi
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/TGUlwu4 permanent;/a\ \terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
