#!/usr/bin/env bash
# Install haproxy
sudo apt-get update
sudo apt-get -y install haproxy
sudo printf "\n frontend holberton
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
    mode http
    balance roundrobin
    server 4639-web-01  54.175.45.148
    server 4639-web-02  52.207.249.170" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
